{% set name = "pytypes" %}
{% set version = "1.0b5" %}
{% set sha256 = "a28f6c7d01c91c9b4a81b4f9523cd0ce620edec3cd30bc389a34540ba3bd9de4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - typestubs=pytypes.stubfile_2_converter:main


requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - typing

test:
  commands:
    - typestubs -h
  imports:
    - pytypes

about:
  home: https://github.com/Stewori/pytypes
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Typing-toolbox for Python 3 _and_ 2.7 w.r.t. PEP 484.'
  doc_url: https://github.com/Stewori/pytypes
  dev_url: https://github.com/Stewori/pytypes

extra:
  recipe-maintainers:
    - mariusvniekerk
    - stewori
