{% set name = "pytypes" %}
{% set version = "1.0b9" %}
{% set sha256 = "2bed705551d19070281f93b2447cc8d0a179190d59ee9ca102bd03a04989738d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - typestubs=pytypes.stubfile_2_converter:main


requirements:
  host:
    - python >=3.5,<3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.5,<3.9
    - typing

test:
  commands:
    - typestubs -h
  imports:
    - pytypes

about:
  home: https://github.com/Stewori/pytypes
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Typing-toolbox for Python 3 _and_ 2.7 w.r.t. PEP 484.
  doc_url: https://github.com/Stewori/pytypes
  dev_url: https://github.com/Stewori/pytypes

extra:
  recipe-maintainers:
    - mariusvniekerk
    - stewori
