travis:
  secure:
    BINSTAR_TOKEN: W2Kv6d8c8pYQlSEupAgY4e6EjgxpytuCFBlEjaTo7VrDLOIFBCjdhhLXZsQ6PE1e8BV4yLf+053qRZnQ++l1bF3FAkWIAT4LRUAJ60FIPQGgjuPvXuOMEqo4zZBydI5ki4M7ZX+8H+W9M0uWlFaYwsvG44aMdEDP45ZqgVND9/3cvbU1VK8GdAttIwkhS+jdYSCoO/AvZtTTNmGU88teUxsYjpe3WFrBQgJOtpp6sOBULZYgTKm/ceeg1yPMsNx6TAKs8Y7pnwiWwvcqqr/5DI6MCS671sQmT3jmnUM0qi2233YPTOi8PWoDn8wTNj3Lr8r3S1Hba63+da5G4ZqenjsgObEPXpAIa+XoV8ViQvYEUYhHDtgNVSzxX9QsCXqoza+ybBml9k55R3hQL7ynQzzbtfUfW6b1f84X1l7AkpD43hbsDxYTzFvFpydQGPlqMOb6ednCgDG313IKCEh8uvnRzE39dypluZ2tP6yTlpAp+ElTOXKCsmfntxWzcptMs6AEYaefT/eM5cRZMidQxG712HYiK6PYJdkj5K0LVyuvaG7VYGwvhoAU2OsnmnTg+4U/X1IbFvh1fNiSCufW59BkFOkg/bTagBHt9gTIlTzbEdLitNWK7fBwXY0+/sms7vUqS9on6rWTArFnFbd1B467WRKoEbE2VqIJPOKERXs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
