travis:
  secure:
    BINSTAR_TOKEN: xAJOgy8AVxm2BszVj5lsSMntL9Y/Bk8H8TwmNQOkAfsFjjpCC3hHCCGTuJoRUPRjbT6lzX/zM99Rx6/mu5UrP+vWGmYt2wxdQ19olqgBLvLHZptBtJ7STSGAl44NmSXF85ANmtDkt+hpNNLVybLq2uSEHFa/ORmTrwg6XWhziBNasYatiYyD2zQjF9g4fjJecmumNNwmt/mTWqMOdp9la7L5kNj+bPEzWRqa1dnfPcAPcgnMDPXI5wFOX49m+sNFHuPjKxgV9UC2ff7QGFZC8qAFZxwd0bDc4eVg0Cp+LDRZqnOFAYkgGF1bhIV0y+ujdJbufDUg1h8C0WrdH9h477NonjLNqxy7uFEUoq3jLObMk0lqvm8JY5yia5YcVdQ3RPb24BY8NTPQTcYryynNgVOsOIBzMj68Y+d2InJ7s9EszkyxubETBPzMZlunREGX4rufwhOsnyhekXIzF5D65ACkf6GwyDmzb5+cZZpe4yZ8vUBkvMwpN3jY4qfIB+Z8aAkwY1w4UI3oFZDf2Nq3wJPQXzJ7sj5wjTLi6x1yYfN8muvjwcM2y2cunsNy4uS3xotNBZihSbA8+ubAN2mXV2GoHb7ngx+ybMGfL/iHtjtSr5yv+2MmbTX2i7l1XYPW3MHpm9TuuDotDKnzGH8KoWSkhdrySzUdOEoNPJJyCZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
