travis:
  secure:
    BINSTAR_TOKEN: ldhJBaF20Rp0u++DNyYQ81A+tWkoggyxfyx2JO4HOQF1R4kGiTfdtm2KQaTMwacRdbFpG3DLz8gh2B8Zr5xAZ+4uu6cCShRB7bSqGyaFcR3473QhOWMLjR76PUh/3mh0wSnaWwBc89sEgUkDCpyG7MPqRHQ40V/znQxiUXKCWaFNDmxZNPIppIAbImp3SOcKmJU1zj/IV4D2w1KUqPehwIzIGA23gPOCSTPp+0rSwltPB059P/FApGP4AuodcUG7CQ5zOSjV4iukElQr8JE86XXs+tRoUbQ7ROYhxXm3Zw33BkjQtOU4zbU6ylDMriEhV98TdQ78QfWT0fcjYi6oscGSgwRybRCvebykV6nElvXnC6m2Ux7CPkXQ6CIFoTtACrtHuI27oKnLhLEhsGCx5OIfqYaUTv+DHuM0p0YVlFiYmCAaEFi+sz9v9pdXhPD/AD7m5Zc6Thhx7Ujncpmdw3CInDF7UZA78KCtFSSXOjbAE65qGsx81J25CRLArGj3bFBcVcXERPkSAg+M62vE/Es+0q3Tfjb2AaNzneeNe19GjsiM5ZPwR3imgaX3+WFoKw/3HWOFsA+WGYO7izgc+mo/ySONbC1uG8nvxA3CXhnLl6E7Vwd5kyueOo9CuMR5U8Q2cviYfG5+u+LaIkG/JTBPnxlmVM9uG9VmZh2uvaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
