travis:
  secure:
    BINSTAR_TOKEN: yJN+QBblaObvPJPZrlurE31wt1mMiZdvqD9RPi3wI9VV0UAEUL2mI4FdddQCkrFMR0BOD3CqHtl056aqTn2DPPguIYUop5XFD3Cy/GwYJ33KlivAV5ppmB8OUAK7vKw+yf+l7Xg8Cup8ORsrVdIgKT9gu+6KDrmyrvaV6PS9xwFIMKpIG90XKc77o1ivqlAhGX8oT8/fZApo1YslNl4FiE3ICh/8JeTg6Qlc1kkkgLDUcZdgRYeRHzHAddhxdwokHnlK4jAlw8eFwzjWZ1QcJ6gc/OVa1WqJ9K+yRDyogf7myLb9NBCMAslFoP/9M2bmOJTk+fMeRRu+oPiSBCh9lGl7nEKUQ9eccLNUgOOc63bkZc9QhX4D/I+/YUTlMTrKsK08F7831F6ZVN80JVOMRYoN/0VvaILv/Rf75WklZCFESaY9wM5ERV762n1T3iTyrOXjGSCGOuiA6du8LsJbAPrA26cb0Pf2mDrCzt2BS6UJI+kdys6aCC5O+NIR0JFP6sBaqEdPGb4I9tbySH8Dxfy+QM2ySNHM7v2yqvqBS+IoAgM1aDBcWnMAHs8Q1eaT7n8IchieDn3mz92JSC6q4R0cHn9bfqnE8UaJZYY3IrHsTKOU9BIiF5y6ZEfUIMtEjlpY4QLgXjWysHFBl5/c4hkiXgC+S3xIy3KHTaDiKYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
